framework: 'keras'

project: 'image-classification'

base_path: './'  #/google drive

wandb: True
train:
  # dir: './results/resnet34.0.policy'
  batch_size: 16
  epochs: 32
  learning_rate: 0.0001

optimizer:
  name: 'adam'
  params:
    lr: 0.0005